import { Image } from "@/api/property/type";
import { AutocompleteObject, CONTRACT_TYPE } from "@/type";

export interface AddPropertyValues {
  name: string;
  city: AutocompleteObject | null;
  propertyType: AutocompleteObject | null;
  region: AutocompleteObject | null;
  furnish: AutocompleteObject | null;
  address: string;
  detail: string;
  contract_type: CONTRACT_TYPE;
  cladding: AutocompleteObject | null;
  features: AutocompleteObject[];
  water_front: boolean;
  images: string[];
  old_images?: Image[];
  images_delete_ids?: string[];
  bed_rooms: number;
  bath_rooms: number;
  kitchens: number;
  floors: number;
  floor_level: number;
  sqft_living: number;
  sqft_living_15: number;
  sqft_lot: number;
  sqft_lot_15: number;
  sqft_above: number;
  sqft_basement: number;
  view: number | null;
  condition: number | null;
  grade: number | null;
  yr_built: string;
  yr_renovated: string;
  zip_code: string;
  lat: string;
  long: string;
  north: boolean;
  south: boolean;
  east: boolean;
  west: boolean;
  price: number;
}
